Windows
graduway/psick pull request #10
Opened 2018-02-09 10:28 UTC by shapi78

2018-02-09 10:52 UTC, antgel requested changes
Generally great, few small changes

2018-02-09 10:52 UTC, antgel commented on Puppetfile
> +  :branch => 'windows'
This should be merged to master, please open a PR. Then we will submit a PR upstream. :)

2018-02-09 10:52 UTC, antgel commented on hieradata/role/openvpn.yaml
> +    email: 'it@graduway.com'
`development@`

2018-02-09 10:52 UTC, antgel commented on hieradata/role/openvpn.yaml
> +  'client1': {}
What are these 1/2/3? Can we have better identifiers?

2018-02-09 10:52 UTC, antgel commented on hieradata/role/openvpn.yaml
> +    organization: 'graduway.com'
Graduway

2018-02-09 10:52 UTC, antgel commented on hieradata/common.yaml
> +#  hostname: '::psick::hostname'
Please remove commented code.

2018-02-12 14:43 UTC, antgel approved these changes

2018-02-12 14:44 UTC, merged

2018-02-12 14:45 UTC, antgel commented
@alvagante Hi, we forgot to get your review on this stuff. Please let us know what you think, thanks!

2018-02-12 23:14 UTC, alvagante commented on Puppetfile
> +  :git => 'https://github.com/graduway/ec2tagfacts',
We should start to specify versions for each module in Puppetfile, the default latest version is ok for demo purposes, but on real environments it's recommended to specify version names, in order not to have bad surprises when deploying modules in different times / places.
This comment applies not only to these new entries but to all the modules listed in the Puppetfile

2018-02-12 23:14 UTC, alvagante reviewed
Generatty this Looks ok to me