Adding environment variables from facts
graduway/psick pull request #90
Opened 2018-08-15 10:34 UTC by shapi78

Pass puppet facts to environment varibles to use on Jenkins
Fixes #63

2018-08-16 12:47 UTC, alvagante reviewed
Looks ok.

2018-08-21 11:08 UTC, antgel requested changes
Code great, don't want production code sitting on branches, please open PRs to `master` and edit these commits to pull from `master`.

2018-08-21 11:08 UTC, antgel commented on Puppetfile
> +  :branch => 'prod-env'
Please open a PR to merge this into our master.

2018-08-21 11:08 UTC, antgel commented on Puppetfile
> +  :branch => 'mail-env'
Please open a PR to merge this into our master.

2018-09-03 11:47 UTC, antgel approved these changes

2018-09-03 11:47 UTC, merged

2018-09-03 12:02 UTC, alvagante commented on Puppetfile
> +mod 'example42-profile', '2.0.4'
Note that current psick module has the psick::profile class which does the same

2018-09-03 12:03 UTC, alvagante commented on site/profile/manifests/profile.pp
> +  	String $template  = '',
Here the $template variable does nothing, can be removed